org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
flutter.useNativeAssets=false
# ✅ Disable Gradle state tracking
org.gradle.workers.max=4
org.gradle.vfs.watch=false
org.gradle.cache.tasks=false
org.gradle.unsafe.isolated-projects=false
android.useNewApkCreator=true
android.enableBuildCache=false