name: detectapp
description: VisionBot Automated Surveillance
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  camera: ^0.10.5
  path_provider: ^2.1.1
  google_mlkit_face_detection: ^0.10.0
  flutter_dotenv: ^5.1.0
  image: ^4.0.17
  google_maps_flutter: ^2.5.3
  latlong2: ^0.9.1
  
  tflite_flutter: ^0.11.0
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  permission_handler: ^11.0.1
  device_info_plus: ^10.0.1
  geolocator: ^9.0.2  
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.0
  # flutter_core: ^1.0.2
  
dependency_overrides:
  sign_in_with_apple: ^6.1.0
   

  flutter_blue_plus: ^1.31.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/facenet.tflite
    - assets/yolov8n.tflite
    - assets/smoking.tflite
    - .env
    - assets/geo/path.geojson
    - assets/geo/boundaries.geojson
    - assets/geo/waypoints.geojson
