name: detectapp
description: VisionBot Surveillance Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.6
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  google_mlkit_face_detection: ^0.10.1
  tflite_flutter: ^0.11.0
  image: ^4.3.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  device_info_plus: ^10.1.2
  geolocator: ^12.0.0
  geocoding: ^2.1.1
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.4
  firebase_storage: ^11.7.7
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/facenet.tflite
    - assets/yolov8n.tflite
    - assets/smoking.tflite