// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApaBAZDuGAP5eeAQTk84YrElAIf2iLN8U',
    appId: '1:747301058022:web:3576e8f5d63fb850891227',
    messagingSenderId: '747301058022',
    projectId: 'visionbot-82c8b',
    authDomain: 'visionbot-82c8b.firebaseapp.com',
    storageBucket: 'visionbot-82c8b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZj3_ulIE3orkZ-g1Kek2h_I_BpVZISo4',
    appId: '1:747301058022:android:0fe66ad3bae4cab8891227',
    messagingSenderId: '747301058022',
    projectId: 'visionbot-82c8b',
    storageBucket: 'visionbot-82c8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkU2eTIShQlqA-Nt3YS5k1dQ6E70e4HH8',
    appId: '1:747301058022:ios:24f618fca7aca7c4891227',
    messagingSenderId: '747301058022',
    projectId: 'visionbot-82c8b',
    storageBucket: 'visionbot-82c8b.firebasestorage.app',
    iosBundleId: 'com.example.detectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkU2eTIShQlqA-Nt3YS5k1dQ6E70e4HH8',
    appId: '1:747301058022:ios:24f618fca7aca7c4891227',
    messagingSenderId: '747301058022',
    projectId: 'visionbot-82c8b',
    storageBucket: 'visionbot-82c8b.firebasestorage.app',
    iosBundleId: 'com.example.detectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApaBAZDuGAP5eeAQTk84YrElAIf2iLN8U',
    appId: '1:747301058022:web:86d7405a5e8e1a81891227',
    messagingSenderId: '747301058022',
    projectId: 'visionbot-82c8b',
    authDomain: 'visionbot-82c8b.firebaseapp.com',
    storageBucket: 'visionbot-82c8b.firebasestorage.app',
  );
}
